/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepoNameRouteImport } from './routes/repo.$name'
import { Route as RepoNameRefRefRouteImport } from './routes/repo.$name.ref.$ref'

const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoNameRoute = RepoNameRouteImport.update({
  id: '/repo/$name',
  path: '/repo/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoNameRefRefRoute = RepoNameRefRefRouteImport.update({
  id: '/ref/$ref',
  path: '/ref/$ref',
  getParentRoute: () => RepoNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/repo/$name': typeof RepoNameRouteWithChildren
  '/repo/$name/ref/$ref': typeof RepoNameRefRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/repo/$name': typeof RepoNameRouteWithChildren
  '/repo/$name/ref/$ref': typeof RepoNameRefRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/repo/$name': typeof RepoNameRouteWithChildren
  '/repo/$name/ref/$ref': typeof RepoNameRefRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/maintenance' | '/repo/$name' | '/repo/$name/ref/$ref'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/maintenance' | '/repo/$name' | '/repo/$name/ref/$ref'
  id: '__root__' | '/' | '/maintenance' | '/repo/$name' | '/repo/$name/ref/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaintenanceRoute: typeof MaintenanceRoute
  RepoNameRoute: typeof RepoNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$name': {
      id: '/repo/$name'
      path: '/repo/$name'
      fullPath: '/repo/$name'
      preLoaderRoute: typeof RepoNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$name/ref/$ref': {
      id: '/repo/$name/ref/$ref'
      path: '/ref/$ref'
      fullPath: '/repo/$name/ref/$ref'
      preLoaderRoute: typeof RepoNameRefRefRouteImport
      parentRoute: typeof RepoNameRoute
    }
  }
}

interface RepoNameRouteChildren {
  RepoNameRefRefRoute: typeof RepoNameRefRefRoute
}

const RepoNameRouteChildren: RepoNameRouteChildren = {
  RepoNameRefRefRoute: RepoNameRefRefRoute,
}

const RepoNameRouteWithChildren = RepoNameRoute._addFileChildren(
  RepoNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaintenanceRoute: MaintenanceRoute,
  RepoNameRoute: RepoNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
